"""Hand-authored telecom support scenarios used to generate the synthetic dataset.

Each scenario is one *root cause* with a known fix. Tickets generated from the
same scenario are "the same problem described in different words".

Field conventions
-----------------
symptoms : 6 paraphrases of the customer-visible problem.
           Indices 0-3 ("corpus family") are used for historical tickets in the
           retrieval corpus; indices 4-5 ("held-out family") are used ONLY for
           evaluation queries. This is how we test vocabulary mismatch without
           leaking phrasing from eval into the corpus.
steps    : [canonical wording, paraphrase] pairs. Canonical wording appears in
           tickets/KB; the paraphrase is used to build supported claims for the
           groundedness experiment (E3) so lexical overlap is not trivially high.
contradiction : a claim that directly contradicts the canonical fix (E3).
wave     : 1 = present at launch; 2 = arrives later (evolving ticket class demo).
"""

from typing import Any

SCENARIOS: list[dict[str, Any]] = [
    # ------------------------------------------------------------------ connectivity
    {
        "id": "CONN_WIFI_EVENING_INTERFERENCE",
        "intent": "connectivity_issue",
        "products": ["router", "broadband"],
        "base_severity": "high",
        "wave": 1,
        "symptoms": [
            "my wifi keeps dropping out every evening around {time}",
            "the wireless connection cuts out repeatedly at night but the broadband light on the router stays green",
            "devices on my wifi lose connection several times each evening",
            "my internet drops on wifi most nights while a cable plugged into the router works fine",
            "every night like clockwork my laptop and phone get kicked off the home network for a few minutes",
            "after dinner time the signal from the hub vanishes and comes back, wired desktop is unaffected",
        ],
        "details": [
            "lots of neighbours' networks show up in the wifi list",
            "it is worse in the living room",
            "the router is next to the TV",
        ],
        "tried": ["restarted the router twice", "moved my laptop closer", "turned wifi off and on"],
        "cause": "Co-channel interference from neighbouring Wi-Fi networks at peak hours on the crowded 2.4 GHz band.",
        "steps": [
            [
                "Confirm the drops only affect Wi-Fi by testing a device on an ethernet cable",
                "Check whether a wired device stays online while wireless devices drop",
            ],
            [
                "Run the router's channel scan and move the 2.4 GHz radio to the least congested channel (1, 6 or 11)",
                "Switch the router's 2.4 GHz channel to whichever of 1, 6 or 11 is least crowded",
            ],
            [
                "Enable the 5 GHz band and connect nearby devices to it",
                "Turn on the 5 GHz network and move close-range devices onto it",
            ],
            [
                "Move the router away from the TV, microwave and metal objects",
                "Relocate the hub away from appliances and metal that cause interference",
            ],
            ["Update the router firmware to the latest version", "Install the newest firmware release on the router"],
        ],
        "contradiction": "Keep all devices on the 2.4 GHz band and disable 5 GHz to stop the evening drops",
        "kb_title": "Fixing evening Wi-Fi dropouts caused by channel interference",
    },
    {
        "id": "CONN_DSL_LINE_NOISE",
        "intent": "connectivity_issue",
        "products": ["broadband"],
        "base_severity": "high",
        "wave": 1,
        "symptoms": [
            "my broadband disconnects whenever the home phone rings",
            "there is crackling on the landline and the internet drops at the same time",
            "the DSL light on my modem keeps flashing and the connection resyncs many times a day",
            "my adsl connection drops several times a day and the phone line sounds noisy",
            "each time someone calls the house the web stops working for a minute",
            "the landline hisses and the internet sync light blinks before going offline",
        ],
        "details": [
            "the house has several phone sockets",
            "it started after some building work",
            "the noise is worse when it rains",
        ],
        "tried": ["restarted the modem", "swapped the phone cable", "unplugged the cordless phone"],
        "cause": "Electrical noise on the copper line, usually a missing microfilter or a faulty internal extension wiring.",
        "steps": [
            [
                "Fit a microfilter on every phone socket that has a phone or device plugged in",
                "Make sure each phone socket in use has a microfilter attached",
            ],
            [
                "Connect the modem to the master socket using the test socket to bypass internal wiring",
                "Plug the modem into the test socket behind the master faceplate to rule out house wiring",
            ],
            [
                "Run a remote line test from the support system to check for noise and line faults",
                "Perform a remote diagnostic of the copper line for noise",
            ],
            [
                "If the line test fails, book an engineer visit to repair the line",
                "Schedule a technician to fix the line when the diagnostic shows a fault",
            ],
        ],
        "contradiction": "Remove all microfilters because they cause the line noise",
        "kb_title": "Broadband drops when the phone rings: line noise and microfilters",
    },
    {
        "id": "CONN_FIBER_ONT_LOS",
        "intent": "connectivity_issue",
        "products": ["fiber"],
        "base_severity": "critical",
        "wave": 1,
        "symptoms": [
            "my fibre is completely down and the ONT has a red LOS light",
            "no internet at all, the fiber box on the wall shows a red light",
            "the optical network terminal shows LOS in red and nothing connects",
            "fiber connection lost, the ONT PON light is off and LOS is red",
            "the little white box where the glass cable comes in is glowing red and we're offline",
            "the wall terminal that the installer fitted has a red alarm lamp and there is no service",
        ],
        "details": [
            "we moved some furniture yesterday",
            "the cable runs behind a cupboard",
            "the router itself looks normal",
        ],
        "tried": ["rebooted the router", "power cycled the ONT", "checked the power socket"],
        "cause": "Loss of optical signal, typically a bent, pinched or disconnected fibre patch lead, or a fault on the network side.",
        "steps": [
            [
                "Check the thin fibre cable into the ONT for sharp bends, kinks or pinching and straighten it",
                "Inspect the fibre lead going into the ONT for kinks or crushing",
            ],
            [
                "Make sure the green fibre connector is fully clicked into the ONT port without touching the fibre end",
                "Reseat the fibre connector firmly in the ONT without touching its tip",
            ],
            [
                "Check the outage map for a fibre fault in the area",
                "Look up the area status page for a known fibre outage",
            ],
            [
                "If LOS stays red, raise a fibre fault and dispatch a field engineer",
                "Book a fibre technician when the LOS light does not clear",
            ],
        ],
        "contradiction": "Unplug the fibre cable and clean the glass tip with a damp cloth to clear the red LOS light",
        "kb_title": "Red LOS light on the fibre ONT",
    },
    {
        "id": "CONN_MOBILE_INDOOR_SIGNAL",
        "intent": "connectivity_issue",
        "products": ["mobile_service"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "I have no mobile signal inside my house",
            "calls drop as soon as I walk indoors and the phone shows one bar",
            "my mobile has poor reception at home but works fine outside",
            "phone signal disappears in my flat so calls and texts fail",
            "indoors the bars on my handset vanish and people can't reach me",
            "I have to stand in the garden to make a call, the house is a dead zone",
        ],
        "details": [
            "the house has thick stone walls",
            "we recently moved",
            "my partner's phone on another network works",
        ],
        "tried": ["restarted the phone", "removed the case", "toggled airplane mode"],
        "cause": "Weak indoor coverage due to building materials or distance from the mast.",
        "steps": [
            ["Check the coverage map for the customer's address", "Look up predicted indoor coverage at the address"],
            [
                "Enable Wi-Fi Calling on the handset so calls route over home broadband",
                "Turn on Wi-Fi Calling so the phone uses the home internet for calls",
            ],
            [
                "Make sure the phone software and carrier settings are up to date",
                "Install pending handset and carrier settings updates",
            ],
            [
                "Offer an indoor signal booster or femtocell if Wi-Fi Calling is not possible",
                "Provide a femtocell or booster where Wi-Fi Calling is unavailable",
            ],
        ],
        "contradiction": "Disable Wi-Fi Calling because it blocks mobile signal indoors",
        "kb_title": "Poor indoor mobile coverage and Wi-Fi Calling",
    },
    {
        "id": "CONN_WIFI_DEVICE_AUTH",
        "intent": "connectivity_issue",
        "products": ["router"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "one of my devices won't connect to the wifi after I changed the password",
            "my laptop says incorrect password for the wifi even though it's right",
            "an older tablet can no longer join the wireless network but phones can",
            "my printer cannot connect to the router since the wifi settings were changed",
            "one gadget keeps saying it can't join the network although everything else is online",
            "the smart TV refuses the network key since I updated the hub's security settings",
        ],
        "details": ["it is an older device", "other devices are fine", "I switched security to WPA3"],
        "tried": ["typed the password again", "restarted the device", "restarted the router"],
        "cause": "Stale saved network profile or the device doesn't support the new security mode (e.g. WPA3-only).",
        "steps": [
            [
                "Forget the saved network on the device and reconnect with the new password",
                "Delete the stored Wi-Fi profile on the device and join again",
            ],
            [
                "Set the router security mode to WPA2/WPA3 mixed so older devices can join",
                "Change the router to WPA2/WPA3 transitional mode for legacy devices",
            ],
            [
                "Check the router's MAC filter or blocked devices list",
                "Review the router's device block list and MAC filtering",
            ],
            [
                "Update the device's network drivers or firmware",
                "Install the latest wireless driver or firmware on the device",
            ],
        ],
        "contradiction": "Set the router to WPA3-only mode so older devices can connect",
        "kb_title": "Device can't join Wi-Fi after a password or security change",
    },
    {
        "id": "CONN_DNS_FAILURE",
        "intent": "connectivity_issue",
        "products": ["broadband"],
        "base_severity": "high",
        "wave": 1,
        "symptoms": [
            "my internet shows connected but websites won't load",
            "I can't browse any sites although the router says it is online",
            "pages time out with DNS errors but apps like WhatsApp still work",
            "the browser says server not found on every website even though wifi is connected",
            "the connection icon looks fine yet nothing opens in Chrome, it says address couldn't be found",
            "online games work but typing any web address just spins and fails",
        ],
        "details": ["the error says DNS_PROBE_FINISHED", "it happens on all devices", "pinging an IP address works"],
        "tried": ["restarted the router", "cleared the browser cache", "tried another browser"],
        "cause": "DNS resolution failure: the configured DNS server is unreachable or the local DNS cache is corrupted.",
        "steps": [
            [
                "Confirm the issue is DNS by pinging an IP address such as 8.8.8.8",
                "Test raw connectivity by pinging a public IP address",
            ],
            ["Flush the DNS cache on the device (ipconfig /flushdns on Windows)", "Clear the device's DNS cache"],
            [
                "Set the router's DNS servers to automatic, or to a public resolver such as 1.1.1.1 and 8.8.8.8",
                "Point the router at automatic DNS or a public DNS resolver",
            ],
            ["Restart the router after changing DNS settings", "Reboot the hub once the DNS change is saved"],
        ],
        "contradiction": "Factory reset the router immediately because DNS errors mean the hardware is faulty",
        "kb_title": "Connected but no websites load (DNS errors)",
    },
    # ------------------------------------------------------------------ speed
    {
        "id": "SPEED_PEAK_CONGESTION",
        "intent": "speed_issue",
        "products": ["broadband"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "my broadband gets very slow every evening between {time} and 11",
            "internet speed drops massively at peak times in the evening",
            "streaming buffers every night even though speeds are fine in the morning",
            "speed tests show a fraction of my plan speed in the evenings",
            "after work hours the connection crawls and video calls freeze, mornings are perfect",
            "come nightfall my downloads slow to a trickle across every device in the house",
        ],
        "details": [
            "wired speed tests are slow too",
            "the whole street seems affected",
            "it has been like this for weeks",
        ],
        "tried": ["restarted the router", "ran speed tests", "disconnected other devices"],
        "cause": "Network congestion at peak hours on the local exchange or cabinet backhaul.",
        "steps": [
            [
                "Run a wired speed test at peak and off-peak times to confirm the slowdown is network-side",
                "Compare cabled speed tests in the evening and in the morning",
            ],
            [
                "Check the network capacity dashboard for congestion on the customer's cabinet",
                "Look up utilisation on the local cabinet or exchange",
            ],
            [
                "Raise a congestion ticket with the network team if utilisation is above threshold",
                "Log a capacity issue with network operations when the cabinet is saturated",
            ],
            [
                "Enable QoS on the router to prioritise video calls during peak hours",
                "Turn on router QoS so calls get priority in busy periods",
            ],
        ],
        "contradiction": "Replace the router because evening slowdowns are always caused by faulty hardware",
        "kb_title": "Slow broadband at peak evening hours",
    },
    {
        "id": "SPEED_FIBER_PLAN_MISMATCH",
        "intent": "speed_issue",
        "products": ["fiber", "router"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "I pay for 500 Mbps fibre but only get about 90",
            "my gigabit fiber never goes above 100 Mbps on speed tests",
            "fiber speeds are stuck at around 94 Mbps even on a wired connection",
            "I upgraded to a faster fibre package but my speed tests haven't improved past 100",
            "the speed I'm billed for is five times what my computer actually measures",
            "no matter what, the fastest download I see is just under a hundred megabits on my glass connection",
        ],
        "details": [
            "I use an old router I bought myself",
            "the ethernet cable is quite old",
            "speed is the same on every device",
        ],
        "tried": ["restarted everything", "tested at night and day", "used a different laptop"],
        "cause": "A bottleneck in the customer's equipment: a router or ethernet cable limited to 100 Mbps (Fast Ethernet / Cat5).",
        "steps": [
            [
                "Check the negotiated link speed on the computer's network adapter (100 Mbps vs 1 Gbps)",
                "Look at the adapter's link rate to see if it negotiates only 100 Mbps",
            ],
            ["Replace old Cat5 ethernet cables with Cat5e or Cat6", "Swap the ethernet cable for a Cat5e/Cat6 one"],
            [
                "Confirm the router has gigabit WAN and LAN ports; replace it with the supported fibre router if not",
                "Make sure the router supports gigabit ports, otherwise provide the approved fibre router",
            ],
            [
                "Re-run a wired speed test directly from the ONT or router",
                "Repeat the speed test on a cable straight from the router",
            ],
        ],
        "contradiction": "Downgrade the plan to 100 Mbps since the line cannot carry more",
        "kb_title": "Fibre speed stuck at 100 Mbps: checking cables and router ports",
    },
    {
        "id": "SPEED_5G_FALLBACK",
        "intent": "speed_issue",
        "products": ["5g_service", "mobile_service"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "my phone stays on 4G even in 5G areas and data is slow",
            "I have a 5G plan but my phone only shows LTE",
            "5G icon never appears and mobile data is sluggish",
            "my new 5G phone keeps falling back to 4G with slow speeds",
            "the network indicator never switches to the faster mode I'm paying for, downloads are poor",
            "my handset is meant to support the next-generation network but only shows the older one",
        ],
        "details": [
            "the coverage map says 5G is available",
            "my colleague gets 5G in the same office",
            "I got the phone abroad",
        ],
        "tried": ["restarted the phone", "toggled airplane mode", "reset network settings"],
        "cause": "5G disabled in handset settings, outdated carrier settings, or an old SIM that is not 5G-provisioned.",
        "steps": [
            [
                "Set the phone's preferred network type to 5G/Auto in mobile network settings",
                "Change the handset network mode to 5G or automatic",
            ],
            [
                "Install the latest carrier settings and phone software update",
                "Update the phone OS and carrier profile",
            ],
            [
                "Check that the SIM is 5G-enabled and replace older SIMs",
                "Verify the SIM supports 5G and swap it if it is an old card",
            ],
            [
                "Confirm 5G is provisioned on the account and the handset model is supported",
                "Make sure the line has 5G enabled and the device is compatible",
            ],
        ],
        "contradiction": "Disable 5G in the phone settings to make 5G appear",
        "kb_title": "Phone stuck on 4G with a 5G plan",
    },
    {
        "id": "SPEED_MOBILE_DATA_CAP",
        "intent": "speed_issue",
        "products": ["mobile_service"],
        "base_severity": "low",
        "wave": 1,
        "symptoms": [
            "my mobile data became extremely slow halfway through the month",
            "data speed dropped to almost nothing after I used a lot this month",
            "mobile internet is throttled since around the 20th of the month",
            "my phone data was fast until last week and now pages barely load",
            "since I watched a lot of videos recently my handset browsing has become painfully sluggish",
            "towards the end of every billing cycle my cellular internet slows to a crawl",
        ],
        "details": ["I've been streaming a lot", "I got a text about usage", "wifi at home is fine"],
        "tried": ["restarted the phone", "turned data off and on", "cleared apps"],
        "cause": "The plan's fair-usage allowance has been reached and speed is reduced until the next bill cycle.",
        "steps": [
            [
                "Check the data usage against the plan's fair-usage allowance in the account",
                "Review this month's data consumption versus the allowance",
            ],
            [
                "Explain that speeds are reduced after the allowance until the bill cycle resets",
                "Tell the customer data is slowed once the allowance is used until renewal",
            ],
            ["Offer a data add-on or a higher-allowance plan", "Suggest a top-up bundle or bigger data plan"],
            [
                "Set up usage alerts so the customer is notified at 80% of the allowance",
                "Turn on notifications when 80% of data is consumed",
            ],
        ],
        "contradiction": "Reset the network settings because throttling after heavy use is a phone fault",
        "kb_title": "Mobile data slowed after reaching the usage allowance",
    },
    {
        "id": "SPEED_WIFI_COVERAGE_ROOMS",
        "intent": "speed_issue",
        "products": ["router"],
        "base_severity": "low",
        "wave": 1,
        "symptoms": [
            "wifi is really slow upstairs but fine next to the router",
            "speeds in the back bedroom are terrible on wifi",
            "the wireless signal is weak in some rooms so video calls stutter",
            "my home office at the far end of the house gets very slow wifi",
            "only the rooms far away from the hub get poor speeds, near it everything flies",
            "on the top floor the network barely works while downstairs is quick",
        ],
        "details": ["the house has three floors", "the router is in a cupboard", "the walls are brick"],
        "tried": ["restarted the router", "moved the laptop around", "bought a cheap repeater"],
        "cause": "Insufficient Wi-Fi coverage due to distance, walls or router placement.",
        "steps": [
            [
                "Move the router to a central, elevated, open position rather than a cupboard",
                "Place the hub somewhere central and high, not enclosed",
            ],
            [
                "Add a mesh Wi-Fi extender or booster disc for distant rooms",
                "Install mesh units to cover rooms far from the router",
            ],
            [
                "Use the 5 GHz band near the router and 2.4 GHz for distant rooms",
                "Prefer 5 GHz close by and 2.4 GHz further away",
            ],
            [
                "Run a cable or powerline adapter to the home office for a wired connection",
                "Use a powerline kit or ethernet cable for the office",
            ],
        ],
        "contradiction": "Put the router inside a closed metal cabinet to boost the signal upstairs",
        "kb_title": "Improving Wi-Fi coverage in distant rooms",
    },
    # ------------------------------------------------------------------ billing
    {
        "id": "BILL_DOUBLE_CHARGE",
        "intent": "billing_dispute",
        "products": ["billing_system"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "I have been charged twice for this month's bill",
            "my bank statement shows two identical payments to you",
            "the monthly payment was taken two times from my account",
            "I got billed double for the same invoice",
            "the same amount left my bank twice on the same day for my phone account",
            "you debited my card for the subscription on two occasions this cycle",
        ],
        "details": [
            "I paid manually and the direct debit also went out",
            "both transactions are the same amount",
            "I'm now overdrawn",
        ],
        "tried": ["checked my online account", "called my bank", "looked at my invoices"],
        "cause": "A duplicate payment, usually a manual payment plus the scheduled direct debit for the same invoice.",
        "steps": [
            [
                "Verify both transactions in the payments ledger and confirm they are for the same invoice",
                "Check the payment history for two payments against one invoice",
            ],
            [
                "Raise a refund for the duplicate payment to the original payment method",
                "Issue a refund of the extra payment back to the card or bank",
            ],
            [
                "Tell the customer refunds take 5-7 working days to appear",
                "Advise that the money will be back within 5 to 7 business days",
            ],
            [
                "Offer a goodwill credit if the customer incurred bank charges",
                "Apply a goodwill credit to cover any overdraft fees",
            ],
        ],
        "contradiction": "Duplicate payments cannot be refunded and will be kept as account credit only",
        "kb_title": "Handling duplicate payments and refunds",
    },
    {
        "id": "BILL_PREMIUM_SMS",
        "intent": "billing_dispute",
        "products": ["billing_system", "mobile_service"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "there are charges for premium text services I never signed up for",
            "my phone bill has third-party subscription charges I don't recognise",
            "I'm being charged weekly for some SMS service I didn't order",
            "my mobile bill includes content charges from a company I've never heard of",
            "some unknown games subscription keeps getting added to my phone account",
            "mysterious weekly fees from an outside provider are appearing on my statement",
        ],
        "details": ["it's been going on for three months", "my child uses the phone", "I received strange texts"],
        "tried": ["replied STOP to the texts", "checked my bill online", "searched the company name"],
        "cause": "Third-party premium-rate or direct-carrier-billing subscriptions activated on the line.",
        "steps": [
            [
                "Identify the third-party service and its start date from the billing detail",
                "Find the provider name and start date in the itemised bill",
            ],
            [
                "Cancel the subscription and apply a premium services bar on the line",
                "Stop the subscription and block premium-rate services",
            ],
            [
                "Raise a refund request for the disputed third-party charges",
                "Submit a refund claim for the unwanted third-party charges",
            ],
            [
                "Advise the customer to enable spending controls for children's phones",
                "Recommend parental spending limits on the line",
            ],
        ],
        "contradiction": "Third-party charges must be paid and a premium services bar cannot be applied",
        "kb_title": "Unrecognised third-party and premium SMS charges",
    },
    {
        "id": "BILL_PROMO_EXPIRED",
        "intent": "billing_dispute",
        "products": ["billing_system"],
        "base_severity": "low",
        "wave": 1,
        "symptoms": [
            "my bill suddenly went up this month without warning",
            "my monthly price increased a lot and I didn't change anything",
            "why is my invoice much higher than usual",
            "the cost of my package jumped compared to last month",
            "I'm now paying way more each month though I did nothing different",
            "this statement is noticeably bigger than all the previous ones",
        ],
        "details": [
            "I joined on a special offer last year",
            "nothing changed in my usage",
            "the increase is about 15 a month",
        ],
        "tried": ["compared old bills", "checked the website", "looked for emails"],
        "cause": "The introductory promotional discount period ended and the plan reverted to standard price.",
        "steps": [
            [
                "Check the account for an expired promotional discount",
                "Look for a promo discount that has recently ended",
            ],
            [
                "Explain that the introductory offer has ended and the plan returned to the standard price",
                "Tell the customer the intro deal finished and normal pricing now applies",
            ],
            [
                "Offer the current retention deals or a cheaper plan that matches usage",
                "Present available loyalty offers or a lower-cost plan",
            ],
            [
                "Confirm the customer received the end-of-offer notification and note it on the account",
                "Verify the end-of-promotion notice was sent and log it",
            ],
        ],
        "contradiction": "Reapply the expired introductory discount permanently at no change to the contract",
        "kb_title": "Bill increased after a promotional discount ended",
    },
    {
        "id": "BILL_AFTER_CANCELLATION",
        "intent": "billing_dispute",
        "products": ["billing_system"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "I cancelled my service last month but you're still billing me",
            "I'm still being charged even though I closed my account",
            "a direct debit went out after I cancelled my contract",
            "I received a new bill for a service I already terminated",
            "money is still being taken although I ended my subscription weeks ago",
            "despite closing the line I got charged again this month",
        ],
        "details": [
            "I have the cancellation confirmation email",
            "I returned the router",
            "the charge is a full month",
        ],
        "tried": ["checked my email confirmation", "called the bank", "logged into my account"],
        "cause": "The cancellation was not processed at the requested date, or a final pro-rata bill was issued.",
        "steps": [
            [
                "Check the cancellation request date and the date the service was actually ceased",
                "Compare when cancellation was requested with when the service stopped",
            ],
            [
                "If billed past the cancellation date, credit the charges and cancel the direct debit",
                "Refund charges after the cease date and stop the direct debit",
            ],
            [
                "Explain any legitimate final pro-rata charges or notice-period fees",
                "Clarify any valid final partial-month or notice charges",
            ],
            [
                "Confirm the account is closed and send written confirmation",
                "Send the customer a closure confirmation in writing",
            ],
        ],
        "contradiction": "Customers must keep paying for three months after cancellation regardless of the cease date",
        "kb_title": "Charged after cancelling a service",
    },
    {
        "id": "BILL_ETF_HOME_MOVE",
        "intent": "billing_dispute",
        "products": ["billing_system", "broadband"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "I was charged an early termination fee because I moved house",
            "you billed me a cancellation fee when I moved to an area you don't cover",
            "an exit fee appeared on my final bill after relocating",
            "I'm disputing the early cancellation charge since I had to move",
            "a penalty for leaving the contract early was applied even though I relocated",
            "my last statement included a big break fee after moving to a new address",
        ],
        "details": ["the new address has no coverage", "I was offered no alternative", "the fee is over 100"],
        "tried": ["checked the contract", "asked about moving the service", "read the terms"],
        "cause": "Early termination fee applied on cancellation; home-move waivers apply when service is unavailable at the new address.",
        "steps": [
            [
                "Check whether the service is available at the customer's new address",
                "Verify coverage at the new address",
            ],
            [
                "If service is unavailable at the new address, waive the early termination fee under the home-move policy",
                "Remove the exit fee where the new address has no coverage per the moving policy",
            ],
            [
                "If service is available, offer to transfer the contract to the new address instead",
                "Offer a home move of the existing contract when coverage exists",
            ],
            ["Issue a corrected final bill", "Send an amended final invoice"],
        ],
        "contradiction": "Early termination fees are never waived, even when there is no coverage at the new address",
        "kb_title": "Early termination fees when moving home",
    },
    # ------------------------------------------------------------------ hardware
    {
        "id": "HW_ROUTER_OVERHEATING",
        "intent": "hardware_problem",
        "products": ["router"],
        "base_severity": "high",
        "wave": 1,
        "symptoms": [
            "my router keeps rebooting itself several times a day",
            "the router randomly restarts and is very hot to touch",
            "the router lights all go off and it reboots on its own",
            "my hub restarts by itself and drops everyone off the internet",
            "the box that gives us internet turns itself off and on again repeatedly and feels warm",
            "several times a day the home gateway cycles its power without anyone touching it",
        ],
        "details": ["it sits on top of the set-top box", "it's in a closed cabinet", "it's about four years old"],
        "tried": ["moved the router", "factory reset it", "changed the power socket"],
        "cause": "Overheating or a failing power supply causing spontaneous reboots.",
        "steps": [
            [
                "Place the router upright in a ventilated spot, not in a cabinet or on other electronics",
                "Give the hub space and airflow away from other devices",
            ],
            [
                "Check the router's event log for thermal or power-related restarts",
                "Review the router logs for overheating or power events",
            ],
            ["Update the router firmware", "Apply the latest router firmware"],
            [
                "If reboots continue, replace the router and power adapter",
                "Send a replacement router and PSU if it keeps restarting",
            ],
        ],
        "contradiction": "Wrap the router in a cover to keep dust out, which stops the reboots",
        "kb_title": "Router rebooting on its own",
    },
    {
        "id": "HW_MODEM_NO_POWER",
        "intent": "hardware_problem",
        "products": ["modem"],
        "base_severity": "critical",
        "wave": 1,
        "symptoms": [
            "my modem is completely dead with no lights at all",
            "the modem won't turn on, the power light stays off",
            "no lights on the modem even after plugging it into another socket",
            "my cable modem has stopped powering on",
            "the device that connects us to the internet shows no signs of life whatsoever",
            "pressing the power button on the cable box does nothing and it's dark",
        ],
        "details": [
            "there was a power cut last night",
            "the adapter makes a buzzing sound",
            "the socket works for other things",
        ],
        "tried": ["tried a different socket", "pressed the power button", "checked the fuse"],
        "cause": "Failed power adapter or modem hardware failure, often after a power surge.",
        "steps": [
            [
                "Confirm the wall socket works and the power adapter is firmly connected",
                "Check the power outlet and adapter connection",
            ],
            ["Test with a compatible replacement power adapter if available", "Try a known-good power supply"],
            [
                "If the modem still has no lights, send a replacement modem by next-day delivery",
                "Dispatch a new modem with next-day shipping when it stays dark",
            ],
            [
                "Offer a mobile data hotspot while the replacement is in transit",
                "Provide a temporary 4G hotspot until the new device arrives",
            ],
        ],
        "contradiction": "Open the modem casing and check the internal fuse yourself",
        "kb_title": "Modem has no power lights",
    },
    {
        "id": "HW_RESET_LOST_CONFIG",
        "intent": "hardware_problem",
        "products": ["router", "broadband"],
        "base_severity": "high",
        "wave": 1,
        "symptoms": [
            "I factory reset my router and now there's no internet",
            "after pressing the reset button the router connects to wifi but not the internet",
            "the router was reset and the internet light is now red",
            "I reset my modem router and it no longer gets online",
            "I held down the little pinhole button on the hub and since then the web is gone",
            "following a full reset of the box, devices join it but nothing loads online",
        ],
        "details": [
            "it was a third-party router",
            "I lost the sticker with details",
            "the wifi name changed back to default",
        ],
        "tried": ["restarted it again", "checked cables", "tried the default password"],
        "cause": "Factory reset wiped the broadband login (PPPoE username/password) or VLAN settings.",
        "steps": [
            [
                "Log in to the router admin page using the default credentials on the label",
                "Open the router admin interface with the default login on the sticker",
            ],
            [
                "Re-enter the broadband PPPoE username and password from the account",
                "Reconfigure the PPPoE credentials provided for the account",
            ],
            [
                "Set the WAN VLAN ID required by the network if using a third-party router",
                "Configure the correct VLAN tag on the WAN for non-supplied routers",
            ],
            ["Reconfigure the Wi-Fi name and password", "Set the wireless network name and key again"],
        ],
        "contradiction": "Reset the router again repeatedly until the internet light turns green",
        "kb_title": "No internet after a router factory reset",
    },
    {
        "id": "HW_SIM_NOT_DETECTED",
        "intent": "hardware_problem",
        "products": ["mobile_service"],
        "base_severity": "high",
        "wave": 1,
        "symptoms": [
            "my phone says no SIM card inserted",
            "the SIM is not detected and I can't make calls",
            "invalid SIM error keeps showing on my phone",
            "my mobile suddenly lost service and shows SIM not recognised",
            "the handset claims there's no card even though it's definitely in there",
            "out of nowhere my phone stopped seeing the little chip and I have no network",
        ],
        "details": ["I dropped the phone recently", "the SIM is several years old", "another SIM works in my phone"],
        "tried": ["restarted the phone", "took the SIM out and put it back", "cleaned the SIM"],
        "cause": "Damaged or worn SIM card, or a SIM tray/reader issue.",
        "steps": [
            [
                "Power off the phone, reseat the SIM in the tray and restart",
                "Turn the phone off, reinsert the SIM card and power it on",
            ],
            [
                "Test the SIM in another phone to isolate SIM versus handset",
                "Try the SIM in a different handset to see if the card is at fault",
            ],
            [
                "If the SIM fails in other phones, issue a replacement SIM and keep the same number",
                "Send a new SIM on the same number when the card is faulty",
            ],
            [
                "If the SIM works elsewhere, refer the handset for repair",
                "Direct the customer to handset repair if the SIM works in another phone",
            ],
        ],
        "contradiction": "Cancel the number and issue a new number because SIM errors cannot be fixed",
        "kb_title": "Phone shows 'No SIM' or 'Invalid SIM'",
    },
    {
        "id": "HW_ETHERNET_PORT_DEAD",
        "intent": "hardware_problem",
        "products": ["router"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "one of the ethernet ports on my router has stopped working",
            "my PC gets no connection when plugged into the router's LAN port",
            "the wired connection doesn't work and the port light never comes on",
            "the router's network socket isn't giving my desktop internet any more",
            "plugging the cable into the back of the hub does nothing for my computer",
            "my games console won't get online through the cable, no little light by the socket",
        ],
        "details": ["the other ports work", "wifi is fine", "the cable was pulled hard"],
        "tried": ["used a different cable", "restarted the router", "restarted the PC"],
        "cause": "Faulty LAN port, damaged cable, or network adapter issue on the computer.",
        "steps": [
            ["Try a different LAN port and a known-good ethernet cable", "Test another router port with another cable"],
            [
                "Check the computer's network adapter is enabled and drivers are current",
                "Make sure the PC's ethernet adapter is on and up to date",
            ],
            ["If multiple ports fail, replace the router", "Swap the router when more than one port is dead"],
        ],
        "contradiction": "Ethernet ports never fail, so the customer must buy a new computer",
        "kb_title": "Router ethernet port not working",
    },
    # ------------------------------------------------------------------ activation
    {
        "id": "ACT_FIBER_NOT_PROVISIONED",
        "intent": "service_activation",
        "products": ["fiber"],
        "base_severity": "high",
        "wave": 1,
        "symptoms": [
            "the engineer installed my fibre yesterday but there's still no service",
            "my new fiber line was installed but isn't activated",
            "installation is complete but the ONT shows no connection to the network",
            "my fibre activation date has passed and nothing works",
            "the technician fitted all the equipment but we still can't get online at the new house",
            "the glass connection was put in days ago and still hasn't gone live",
        ],
        "details": ["the PON light is flashing", "I got an activation email", "the router shows no WAN"],
        "tried": ["rebooted the router", "rebooted the ONT", "checked the cables"],
        "cause": "Order not yet provisioned on the OLT or ONT serial not registered to the account.",
        "steps": [
            [
                "Check the order status and that the ONT serial number is registered to the account",
                "Verify the order is complete and the ONT serial is linked to the account",
            ],
            ["Trigger provisioning of the service profile on the OLT", "Push the service profile to the OLT"],
            [
                "Ask the customer to reboot the ONT and router after provisioning",
                "Have the customer power cycle the ONT and router once provisioned",
            ],
            [
                "If still not working, escalate to the provisioning team",
                "Escalate to provisioning when the line stays down",
            ],
        ],
        "contradiction": "Ask the customer to wait 30 days because fibre activation cannot be expedited",
        "kb_title": "New fibre installed but not active",
    },
    {
        "id": "ACT_SIM_PENDING",
        "intent": "service_activation",
        "products": ["mobile_service"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "my new SIM card still isn't active after two days",
            "I got a new SIM but it says emergency calls only",
            "the SIM I ordered has not been activated yet",
            "new mobile line not working since I inserted the SIM",
            "the card that arrived in the post only allows SOS calls",
            "I put the replacement chip in my phone and it still has no service at all",
        ],
        "details": ["I ordered online", "I haven't uploaded ID yet", "I got an email asking for documents"],
        "tried": ["restarted the phone", "reinserted the SIM", "waited 24 hours"],
        "cause": "Activation pending identity verification (KYC) or the activation step was not completed.",
        "steps": [
            [
                "Check the SIM order status and whether identity verification is pending",
                "Look up whether ID verification is outstanding for the order",
            ],
            [
                "Ask the customer to complete identity verification in the app",
                "Get the customer to finish ID checks in the app",
            ],
            [
                "Manually trigger SIM activation once verification is complete",
                "Activate the SIM from the back office after verification",
            ],
            [
                "Ask the customer to restart the phone after activation",
                "Have the customer reboot the handset once activated",
            ],
        ],
        "contradiction": "SIMs activate automatically, so identity verification is never required",
        "kb_title": "New SIM not activating",
    },
    {
        "id": "ACT_PORT_IN_STUCK",
        "intent": "service_activation",
        "products": ["mobile_service"],
        "base_severity": "high",
        "wave": 1,
        "symptoms": [
            "my number transfer from my old provider is stuck",
            "porting my number has failed and I've got a temporary number",
            "I gave you my PAC code but my number still hasn't moved",
            "the number port is pending for days",
            "I still can't use my old phone number with you even though I switched last week",
            "moving my existing mobile number over to you just hasn't happened",
        ],
        "details": [
            "the old provider says it was released",
            "I used a business number",
            "the name on the accounts differs",
        ],
        "tried": ["checked the code", "called the old provider", "restarted the phone"],
        "cause": "Port request rejected or delayed due to a mismatched/expired porting code or account details.",
        "steps": [
            [
                "Check the port request status and any rejection reason",
                "Review the port order status and the rejection code",
            ],
            [
                "Verify the PAC or porting code is valid, unexpired and matches the number",
                "Confirm the transfer code is correct and still valid",
            ],
            ["Resubmit the port request with corrected details", "Re-raise the port with fixed information"],
            [
                "Tell the customer the port completes within one working day of a valid request",
                "Advise that porting finishes within one business day once accepted",
            ],
        ],
        "contradiction": "Numbers cannot be transferred between providers, so the customer must keep the temporary number",
        "kb_title": "Number porting delayed or failed",
    },
    {
        "id": "ACT_5G_NOT_PROVISIONED",
        "intent": "service_activation",
        "products": ["5g_service"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "I switched to the 5G plan but 5G isn't enabled on my line",
            "my plan upgrade to 5G hasn't been activated",
            "the account says 5G plan but the network won't give me 5G access",
            "5G add-on purchased but not working on my number",
            "I paid for the faster next-gen tier on my mobile yet the line never received it",
            "since changing tariff to include the newest network I still can't use it",
        ],
        "details": ["my phone is 5G capable", "it changed on my bill", "5G worked on a friend's SIM in my phone"],
        "tried": ["restarted the phone", "updated software", "reset network settings"],
        "cause": "The 5G service flag was not provisioned on the line after the plan change.",
        "steps": [
            ["Check that the 5G service flag is provisioned on the line", "Verify the line has the 5G feature applied"],
            ["Re-provision the 5G service if missing", "Apply the 5G feature to the line again"],
            [
                "Ask the customer to restart the handset to refresh network registration",
                "Have the customer reboot the phone to re-register",
            ],
        ],
        "contradiction": "5G plans do not require provisioning, so nothing can be done on the account",
        "kb_title": "5G plan active but 5G not provisioned",
    },
    # ------------------------------------------------------------------ plan change
    {
        "id": "PLAN_UPGRADE_NOT_APPLIED",
        "intent": "plan_change",
        "products": ["broadband"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "I upgraded my broadband package but the speed hasn't changed",
            "I'm paying for the faster plan now but still getting my old speed",
            "the upgrade went through on my bill but the line speed is the same",
            "my speed upgrade hasn't taken effect",
            "the new tier I moved to costs more but my connection is exactly as before",
            "a week after switching to the premium package nothing feels any quicker",
        ],
        "details": ["the upgrade was three days ago", "I got a confirmation email", "speed tests are identical"],
        "tried": ["ran speed tests", "restarted the laptop", "used a cable"],
        "cause": "New speed profile not yet applied to the line, or the router hasn't re-synced to pick it up.",
        "steps": [
            [
                "Confirm the upgrade order is complete and the new speed profile is applied",
                "Verify the order finished and the faster profile is on the line",
            ],
            [
                "Ask the customer to restart the router so the line re-syncs at the new profile",
                "Have the router rebooted so it re-syncs to the new speed",
            ],
            ["Run a line check to confirm the synced speed", "Check the line sync rate"],
            [
                "If the profile is not applied, escalate to provisioning",
                "Escalate to provisioning if the profile is missing",
            ],
        ],
        "contradiction": "Speed upgrades take three months to apply and cannot be checked",
        "kb_title": "Speed upgrade not applied",
    },
    {
        "id": "PLAN_DOWNGRADE_CONTRACT",
        "intent": "plan_change",
        "products": ["billing_system"],
        "base_severity": "low",
        "wave": 1,
        "symptoms": [
            "I want to move to a cheaper plan but was told I can't",
            "how can I downgrade my package to save money",
            "I'd like a smaller plan because my current one is too expensive",
            "can I reduce my plan before my contract ends",
            "I'm looking to pay less each month by switching to a basic tier",
            "is there any way to lower my package while I'm still tied in",
        ],
        "details": ["I have 8 months left on contract", "I barely use the data", "money is tight"],
        "tried": ["looked online", "used the chat", "checked my contract"],
        "cause": "Downgrades within the minimum term are restricted; eligibility depends on contract end date.",
        "steps": [
            [
                "Check the contract end date and downgrade eligibility",
                "Look up when the minimum term ends and whether a downgrade is allowed",
            ],
            [
                "Explain the downgrade options available now and from the contract end date",
                "Describe what can be changed now versus at contract end",
            ],
            [
                "Offer usage-matched add-on removal or retention discounts to reduce cost",
                "Suggest removing unused add-ons or a loyalty discount",
            ],
            [
                "Schedule the downgrade for the earliest eligible date if the customer agrees",
                "Book the plan change for the first eligible date",
            ],
        ],
        "contradiction": "Downgrades are always free and immediate at any point in the contract",
        "kb_title": "Downgrading a plan during the minimum term",
    },
    {
        "id": "PLAN_ADD_LINE",
        "intent": "plan_change",
        "products": ["mobile_service"],
        "base_severity": "low",
        "wave": 1,
        "symptoms": [
            "I want to add another line to my family plan",
            "how do I add my daughter's phone to my account",
            "can I put an extra SIM on my existing plan",
            "I'd like to add a second mobile number to my plan",
            "we need one more phone connection under my bundle for my son",
            "looking to include my partner's mobile on our shared package",
        ],
        "details": ["she has a phone already", "I want to share data", "I'm the account holder"],
        "tried": ["looked in the app", "checked the website"],
        "cause": "Customer request to add a line; requires account holder verification and plan eligibility.",
        "steps": [
            ["Verify the account holder's identity", "Confirm the caller is the account owner"],
            [
                "Check the plan's maximum lines and shared data options",
                "Look up how many lines and shared data the plan allows",
            ],
            ["Add the new line and send a SIM or eSIM", "Create the additional line and ship a SIM or provide an eSIM"],
            ["Explain the monthly cost change on the next bill", "Describe how the next bill will change"],
        ],
        "contradiction": "Extra lines can only be added by opening a completely separate account",
        "kb_title": "Adding a line to a family plan",
    },
    # ------------------------------------------------------------------ technical support
    {
        "id": "TECH_EMAIL_SETUP",
        "intent": "technical_support",
        "products": ["email_service"],
        "base_severity": "low",
        "wave": 1,
        "symptoms": [
            "I can't set up my email account in Outlook",
            "my email stopped sending from my mail app",
            "how do I configure my email on my new phone",
            "outgoing mail fails with an SMTP error",
            "my new laptop's mail program won't send or receive from my mailbox",
            "messages sit in the outbox and never go out from my provider mailbox",
        ],
        "details": ["it worked on my old computer", "it asks for my password repeatedly", "receiving works"],
        "tried": ["re-entered my password", "removed and re-added the account"],
        "cause": "Incorrect IMAP/SMTP server settings, port or authentication.",
        "steps": [
            [
                "Use IMAP server mail.example-telco.com on port 993 with SSL",
                "Set incoming IMAP to mail.example-telco.com, port 993, SSL",
            ],
            [
                "Use SMTP server smtp.example-telco.com on port 587 with STARTTLS and authentication enabled",
                "Set outgoing SMTP to smtp.example-telco.com, port 587, STARTTLS, auth on",
            ],
            [
                "Reset the email password from the account portal if authentication keeps failing",
                "Change the mailbox password in the portal when login fails",
            ],
        ],
        "contradiction": "Use SMTP port 25 with no authentication for outgoing email",
        "kb_title": "Email client settings (IMAP/SMTP)",
    },
    {
        "id": "TECH_PORT_FORWARDING",
        "intent": "technical_support",
        "products": ["router"],
        "base_severity": "low",
        "wave": 1,
        "symptoms": [
            "my console says NAT type strict and I can't join online games",
            "I need to open ports on my router for gaming",
            "how do I set up port forwarding on my router",
            "online multiplayer won't connect because of NAT",
            "party chat fails and the game shows a restrictive network warning",
            "my friends can't join my lobby, the Xbox reports a closed network type",
        ],
        "details": ["I use a PlayStation", "UPnP may be off", "I host game servers"],
        "tried": ["restarted the console", "restarted the router"],
        "cause": "Router NAT restricts inbound connections; UPnP disabled or ports not forwarded.",
        "steps": [
            ["Enable UPnP in the router settings", "Switch on UPnP on the router"],
            [
                "Give the console a reserved IP address in the router DHCP settings",
                "Reserve a fixed local IP for the console",
            ],
            [
                "Forward the game's required ports to the console's reserved IP",
                "Create port-forwarding rules for the game ports to that IP",
            ],
            ["Restart the console and re-test the NAT type", "Reboot the console and run the network test again"],
        ],
        "contradiction": "Put the console in the router DMZ and disable the firewall permanently as the first step",
        "kb_title": "Strict NAT and port forwarding for gaming",
    },
    {
        "id": "TECH_VOICEMAIL_SETUP",
        "intent": "technical_support",
        "products": ["mobile_service"],
        "base_severity": "low",
        "wave": 1,
        "symptoms": [
            "I can't set up my voicemail",
            "my voicemail isn't working and callers can't leave messages",
            "how do I access my voicemail",
            "calls aren't diverting to voicemail when I don't answer",
            "people tell me it just rings out instead of letting them record a message",
            "I never get any recorded messages when I miss calls",
        ],
        "details": ["I'm on a new phone", "I forgot my PIN", "visual voicemail shows an error"],
        "tried": ["called the voicemail number", "restarted my phone"],
        "cause": "Voicemail not activated, call diversion not set, or PIN unknown.",
        "steps": [
            ["Activate voicemail on the line from the account system", "Enable the voicemail feature on the account"],
            ["Set call diversion on no answer to the voicemail number", "Configure divert-on-no-answer to voicemail"],
            ["Reset the voicemail PIN and send it by SMS", "Issue a new voicemail PIN by text"],
        ],
        "contradiction": "Voicemail cannot be used on new phones",
        "kb_title": "Setting up voicemail",
    },
    {
        "id": "TECH_STATIC_IP",
        "intent": "technical_support",
        "products": ["broadband"],
        "base_severity": "low",
        "wave": 1,
        "symptoms": [
            "I need a static IP address for my home server",
            "can I get a fixed IP on my broadband",
            "my IP address keeps changing and I need it to stay the same",
            "how do I request a static IP for remote access",
            "my CCTV remote viewing breaks because my public address keeps changing",
            "I want a permanent internet address so I can reach my NAS from outside",
        ],
        "details": ["I run a small business from home", "I use a VPN", "I host a website"],
        "tried": ["used dynamic DNS", "looked on the website"],
        "cause": "Dynamic public IP allocation; static IP is an add-on.",
        "steps": [
            [
                "Explain the difference between dynamic and static IP addresses",
                "Describe dynamic versus fixed public IPs",
            ],
            ["Add the static IP add-on to the account", "Apply the fixed IP add-on to the account"],
            [
                "Ask the customer to restart the router to receive the static IP",
                "Have the router rebooted to pick up the fixed IP",
            ],
            ["Suggest dynamic DNS as a free alternative", "Mention dynamic DNS as a no-cost option"],
        ],
        "contradiction": "Static IPs are assigned automatically to every customer",
        "kb_title": "Requesting a static IP address",
    },
    # ------------------------------------------------------------------ account
    {
        "id": "ACC_LOCKED_OUT",
        "intent": "account_management",
        "products": ["account_portal"],
        "base_severity": "low",
        "wave": 1,
        "symptoms": [
            "I'm locked out of my online account",
            "I forgot my password and can't log in",
            "my account got locked after too many login attempts",
            "I can't sign in to the app any more",
            "the website won't let me into my profile after several wrong tries",
            "I've lost access to my customer area and the reset link doesn't arrive",
        ],
        "details": ["I changed my email address", "I use the app", "it says account locked for security"],
        "tried": ["tried resetting the password", "used another browser"],
        "cause": "Account locked after failed attempts or outdated recovery details.",
        "steps": [
            ["Verify the customer's identity with security questions", "Confirm identity with the security check"],
            ["Unlock the account and send a password reset link", "Unlock the profile and email a reset link"],
            ["Update the recovery email or mobile number if it is outdated", "Correct the recovery contact details"],
        ],
        "contradiction": "Locked accounts must be closed and a new account opened",
        "kb_title": "Locked out of the online account",
    },
    {
        "id": "ACC_OTP_NOT_RECEIVED",
        "intent": "account_management",
        "products": ["account_portal"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "I'm not receiving the one-time passcode to log in",
            "the OTP verification code never arrives by SMS",
            "two-factor code doesn't come through so I can't access my account",
            "the login code text isn't being delivered to my phone",
            "the security code you text me for signing in simply never shows up",
            "I wait and wait but the verification message for logging in never comes",
        ],
        "details": ["I changed my number recently", "I'm abroad", "I get other texts fine"],
        "tried": ["requested the code several times", "restarted my phone"],
        "cause": "Outdated mobile number on the account, SMS blocking, or delivery delay.",
        "steps": [
            ["Check the mobile number registered for two-factor authentication", "Verify the 2FA phone number on file"],
            [
                "Update the number after identity verification if it is outdated",
                "Change the 2FA number once identity is confirmed",
            ],
            [
                "Offer email or authenticator-app verification as an alternative",
                "Provide email or app-based codes instead",
            ],
            ["Check for SMS blocking or spam filtering on the handset", "Look for text blocking on the phone"],
        ],
        "contradiction": "Disable two-factor authentication permanently for the account without verification",
        "kb_title": "One-time passcode not received",
    },
    {
        "id": "ACC_CHANGE_HOLDER",
        "intent": "account_management",
        "products": ["account_portal"],
        "base_severity": "low",
        "wave": 1,
        "symptoms": [
            "I need to change the name on the account",
            "how do I transfer the account to my partner",
            "the account holder has passed away and I need to take over",
            "I want to move the account into my name",
            "we'd like the contract put under my wife's name instead of mine",
            "my late father's services need to be switched over to me",
        ],
        "details": ["we have a joint bank account", "I have the death certificate", "we recently married"],
        "tried": ["looked on the website"],
        "cause": "Change of account holder request requiring consent or bereavement process.",
        "steps": [
            [
                "Verify the current account holder or the bereavement documentation",
                "Check the existing holder's consent or bereavement paperwork",
            ],
            [
                "Collect the new holder's identity and payment details",
                "Take the incoming holder's ID and payment method",
            ],
            [
                "Complete the transfer of ownership without interrupting service",
                "Transfer ownership while keeping the service live",
            ],
        ],
        "contradiction": "Ownership can be transferred without any verification of the current holder",
        "kb_title": "Changing the account holder",
    },
    {
        "id": "ACC_AUTOPAY_FAILING",
        "intent": "account_management",
        "products": ["billing_system", "account_portal"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "my automatic payment keeps failing",
            "autopay was declined and now I have a late fee",
            "my direct debit didn't go through this month",
            "I got a payment failed message but my card is fine",
            "the recurring charge bounced and you've warned me about suspension",
            "my scheduled monthly payment was rejected and I don't know why",
        ],
        "details": ["I got a new card recently", "my bank changed", "there's money in the account"],
        "tried": ["checked my bank", "tried to log in"],
        "cause": "Expired or replaced card details on file, or bank mandate cancelled.",
        "steps": [
            ["Check the payment failure reason code", "Look up why the payment was declined"],
            ["Update the card or bank details on the account", "Replace the stored payment details"],
            ["Take a one-off payment for the outstanding balance", "Process a single payment for the amount due"],
            [
                "Waive the late fee as a one-time courtesy if it was the first failure",
                "Remove the late charge once as goodwill for a first failure",
            ],
        ],
        "contradiction": "Failed autopay automatically cancels the contract and cannot be retried",
        "kb_title": "Automatic payment failing",
    },
    # ------------------------------------------------------------------ outage
    {
        "id": "OUT_AREA_FIBER_CUT",
        "intent": "outage_report",
        "products": ["fiber", "broadband"],
        "base_severity": "critical",
        "wave": 1,
        "symptoms": [
            "the whole neighbourhood has lost internet since this morning",
            "nobody on our street has broadband right now",
            "there's an outage in my area, all my neighbours are offline too",
            "internet is down across the entire estate",
            "everyone around me is without a connection, it's clearly not just my house",
            "the full block went offline at the same moment today",
        ],
        "details": ["there are roadworks nearby", "it started around 9am", "the router shows no signal"],
        "tried": ["restarted the router", "checked with neighbours", "looked online"],
        "cause": "Network outage, e.g. a fibre cable cut by roadworks affecting the area.",
        "steps": [
            ["Check the outage map and incident system for the customer's area", "Look up live incidents for the area"],
            [
                "Link the customer to the existing incident and share the latest estimated fix time",
                "Attach the customer to the open incident and give the ETA",
            ],
            [
                "Offer a mobile data boost or hotspot during the outage",
                "Provide extra mobile data while the area is down",
            ],
            [
                "Apply automatic outage compensation once service is restored",
                "Credit compensation after the outage is fixed",
            ],
        ],
        "contradiction": "Send an engineer to the customer's home to fix the area outage",
        "kb_title": "Area-wide broadband outage",
    },
    {
        "id": "OUT_MOBILE_MAST",
        "intent": "outage_report",
        "products": ["mobile_service"],
        "base_severity": "critical",
        "wave": 1,
        "symptoms": [
            "there's no mobile service anywhere in town today",
            "my phone and everyone else's has no signal in this area",
            "the mobile network is down where I live",
            "calls and data aren't working for anyone around here",
            "nobody in the village can use their handsets since the early hours",
            "all phones on your network around here say no service",
        ],
        "details": ["it started overnight", "other networks work", "it affects the whole family"],
        "tried": ["restarted the phone", "tried airplane mode"],
        "cause": "Mobile mast (cell site) outage or maintenance affecting the area.",
        "steps": [
            [
                "Check the network status page for mast outages near the customer's postcode",
                "Look up cell site incidents by postcode",
            ],
            ["Share the incident reference and estimated restoration time", "Give the incident number and repair ETA"],
            [
                "Enable Wi-Fi Calling as a workaround if the customer has broadband",
                "Turn on Wi-Fi Calling as a stopgap",
            ],
        ],
        "contradiction": "Replace the customer's SIM because area-wide outages are SIM faults",
        "kb_title": "Mobile mast outage in the area",
    },
    {
        "id": "OUT_STORM_LINE_DOWN",
        "intent": "outage_report",
        "products": ["broadband"],
        "base_severity": "critical",
        "wave": 1,
        "symptoms": [
            "after the storm the telephone cable to my house is hanging down",
            "a tree fell on the line and now we have no internet or phone",
            "the overhead cable was damaged in the wind and service is dead",
            "my line has been down since the storm last night",
            "high winds ripped the wire off the pole outside and we're cut off",
            "bad weather brought the overhead wire down near our gate",
        ],
        "details": ["the cable is lying across the drive", "the pole looks damaged", "neighbours are fine"],
        "tried": ["restarted the router"],
        "cause": "Physical damage to overhead line plant from weather.",
        "steps": [
            [
                "Advise the customer to keep clear of the fallen cable and not touch it",
                "Tell the customer to stay away from the downed wire",
            ],
            ["Raise an urgent line damage fault for field repair", "Log a priority physical damage repair"],
            ["Offer a mobile hotspot until the line is repaired", "Provide a temporary hotspot during the repair"],
        ],
        "contradiction": "Ask the customer to reconnect the fallen cable to the pole themselves",
        "kb_title": "Line damaged by storm",
    },
    {
        "id": "OUT_PLANNED_MAINTENANCE",
        "intent": "outage_report",
        "products": ["broadband"],
        "base_severity": "medium",
        "wave": 1,
        "symptoms": [
            "my internet goes off in the middle of the night for a few hours",
            "the connection was down between midnight and 4am",
            "every night this week the broadband stopped working overnight",
            "service cut out late last night and came back in the morning",
            "in the small hours the web connection disappears and returns by dawn",
            "I work night shifts and the home connection keeps vanishing after midnight",
        ],
        "details": ["I work night shifts", "it's only overnight", "I didn't receive any notice"],
        "tried": ["restarted the router"],
        "cause": "Planned network maintenance windows overnight.",
        "steps": [
            [
                "Check the planned maintenance schedule for the customer's exchange",
                "Look up scheduled works for the exchange",
            ],
            ["Confirm the maintenance window and expected completion date", "Give the dates and end time of the works"],
            ["Sign the customer up for maintenance notifications", "Subscribe the customer to works alerts"],
        ],
        "contradiction": "Overnight drops always mean the router is broken and must be replaced",
        "kb_title": "Overnight outages from planned maintenance",
    },
    # ------------------------------------------------------------------ wave 2: new class
    {
        "id": "ROAM_NO_DATA_ABROAD",
        "intent": "roaming_issue",
        "products": ["mobile_service"],
        "base_severity": "high",
        "wave": 2,
        "symptoms": [
            "my mobile data doesn't work now that I'm travelling abroad",
            "I'm overseas and my phone connects to a network but no internet",
            "data roaming isn't working in Spain",
            "since landing in another country I can call but have no mobile internet",
            "on holiday in France the handset shows bars but apps won't load",
            "out of the country my phone gets signal yet nothing online works",
        ],
        "details": ["I have a roaming pass", "the phone shows a foreign network", "texts work"],
        "tried": ["restarted the phone", "toggled airplane mode"],
        "cause": "Data roaming disabled on the handset, wrong network selection, or roaming not enabled on the account.",
        "steps": [
            [
                "Turn on data roaming in the phone's mobile network settings",
                "Enable the data roaming toggle on the handset",
            ],
            [
                "Check roaming is enabled on the account and the roaming pass is active",
                "Verify the account allows roaming and the pass is live",
            ],
            ["Manually select a partner network in network settings", "Pick a partner operator manually"],
            ["Confirm the APN settings are correct", "Check the access point name configuration"],
        ],
        "contradiction": "Turn data roaming off to get mobile data abroad",
        "kb_title": "Mobile data not working abroad",
    },
    {
        "id": "ROAM_BILL_SHOCK",
        "intent": "roaming_issue",
        "products": ["mobile_service", "billing_system"],
        "base_severity": "high",
        "wave": 2,
        "symptoms": [
            "I got a huge roaming bill after my holiday",
            "my bill has hundreds in roaming charges from my trip",
            "I was charged a fortune for using data abroad",
            "roaming charges on my bill are way higher than expected",
            "coming back from vacation I found enormous overseas usage fees",
            "using my phone in another country cost me far more than I was told",
        ],
        "details": ["I thought I had a roaming bundle", "I was in a non-EU country", "I didn't get any usage alerts"],
        "tried": ["checked the bill", "looked at the roaming rates"],
        "cause": "Usage outside included roaming zones or without an active roaming pass; spend caps not set.",
        "steps": [
            [
                "Review the itemised roaming usage by country and date",
                "Check the roaming usage per destination and day",
            ],
            [
                "Check whether a roaming pass was active and which zone the country is in",
                "Confirm the pass status and the destination's zone",
            ],
            [
                "Apply the roaming spend cap rules and credit charges above the cap",
                "Refund roaming charges beyond the spending cap",
            ],
            [
                "Set a roaming spending limit and alerts for future trips",
                "Add a roaming cap and notifications for next time",
            ],
        ],
        "contradiction": "Roaming charges can never be reviewed or credited",
        "kb_title": "Unexpected roaming charges",
    },
    {
        "id": "ROAM_CALLS_FAIL",
        "intent": "roaming_issue",
        "products": ["mobile_service"],
        "base_severity": "high",
        "wave": 2,
        "symptoms": [
            "I can't make or receive calls while abroad",
            "my calls fail when roaming in the US",
            "outgoing calls don't connect since I've been overseas",
            "people can't call me while I'm travelling",
            "in another country my phone shows signal but every call drops instantly",
            "since I flew out for work, dialling home never connects",
        ],
        "details": ["data works", "it's a 4G-only network there", "my phone is older"],
        "tried": ["restarted the phone", "dialled with the country code"],
        "cause": "VoLTE roaming not supported for the handset/network or incorrect dialling format.",
        "steps": [
            ["Dial numbers in international format with the + country code", "Use +country-code format when dialling"],
            [
                "Switch the phone's network mode to allow 3G/4G or select another partner network",
                "Change network mode or pick a different partner network",
            ],
            [
                "Check VoLTE roaming support for the handset on the visited network",
                "Verify VoLTE roaming compatibility",
            ],
            ["Enable Wi-Fi Calling as a workaround", "Turn on Wi-Fi Calling as a workaround"],
        ],
        "contradiction": "Calls abroad only work if Wi-Fi Calling is disabled and data roaming is turned off",
        "kb_title": "Calls failing while roaming",
    },
]

# Pools used for generic sentence parts (not scenario-specific).
OPENERS = ["", "", "Hi,", "Hello,", "Hi there,", "Good morning,", "To whom it may concern,", "Hey,"]
TIMES = ["8pm", "7pm", "9pm", "8 o'clock", "half past seven"]
DURATIONS = [
    "since yesterday",
    "for three days",
    "for about a week",
    "for two weeks",
    "since last month",
    "since Monday",
]
IMPACTS = {
    "business": [
        "I run my business from home and this is costing me money.",
        "We take card payments through this connection and the shop can't trade.",
        "I work from home and keep missing client calls.",
    ],
    "personal": [
        "My kids need it for school work.",
        "It's really disruptive.",
        "I can't watch anything in the evenings.",
    ],
    "none": [""],
}
EMOTIONS = {
    "negative": [
        "This is completely unacceptable.",
        "I'm really fed up with this.",
        "Honestly this is ridiculous and I'm close to leaving.",
        "Very frustrating, please sort it out.",
    ],
    "neutral": ["Please advise.", "Can you look into it?", "Let me know what to do.", "What are my options?"],
    "positive": [
        "Thanks in advance, you've always been helpful.",
        "Appreciate your help as always!",
        "Thank you, your support has been great before.",
    ],
}
CLOSINGS = ["", "", "Thanks.", "Regards.", "Cheers."]

AGENT_INTROS = [
    "Customer reported {summary}.",
    "Investigated {summary}.",
    "Ticket raised for {summary}.",
    "Caller described {summary}.",
]
AGENT_STEP_PREFIXES = ["", "", "Advised customer to: ", "Walked customer through: ", "Agent action: "]
AGENT_OUTCOMES = [
    "Issue resolved and customer confirmed service is working.",
    "Customer confirmed the fix worked. Ticket closed.",
    "Resolved on first contact.",
    "Follow-up call next day confirmed the issue is fixed.",
]
